### ISSUE TITLE
Is there any way to pass information to organisms?

### ISSUE THREAD

**Issue by lamerman** [blaa/PyGene#8]
I found no way to pass any information to organisms except for making this information global. Did I miss something?

**Comment by blaa** [comment]
In my previous project I can see I did someting like this:

    def _create(self, train_periods):
        import new
        args = { <- this are arguments to the organisms.
            'genome': self.genome,
            'subexperiment': self.subexperiment,
            'train_periods': train_periods,
        }
        BeastSpecies =  new.classobj("Beast", (_Beast,), args)  <- create a new subclass.

        # Create population class
        Population = self.loader.load_population("EngineeredPopulation",
                                                 species=BeastSpecies)
        return BeastSpecies, Population


  new.classobj(name, baseclasses, dict)
    This function returns a new class object, with name name, derived from baseclasses (which   
    should be a tuple of classes) and with namespace dict.


So a subclass first, then another subclass with defined dict namespace. It works for me.

**Comment by lamerman** [comment]
Thanks.
